### ISSUE TITLE
Alignment Issue on Dual Monitor Setup

### ISSUE THREAD

**Issue by joseparreiras** [mr-pennyworth/alfred-extra-pane#4] opened 2022-01-17 18:18 UTC
I recently opened an issue on the Better Dictionaries repo https://github.com/mr-pennyworth/alfred-better-dictionaries/issues/12 but later found out the problem was actually due to the Extra Pane. I have a dual monitor setup combining my Macbook and an external display. When I unplug the external display, the app seems to work nicely. On the other hand, when the external display is on I have some issues. As I stated on my previews issue, this does not seem to be a problem with the choice of theme.

**Better Dictionaries**
For example, when I open the Better Dictionaries on my external display, the word preview doesn't show up (as shown on the referred issue)

![image](https://user-images.githubusercontent.com/20421273/149820092-935a0743-c5b7-42cd-9d05-c635b814e88e.png)

When I open it on the MacBook screen, the alignment does not seem right.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/20421273/149820426-d3ed0094-ac18-42cf-ab25-29a02cc094a2.png">

**AsciiMath**
When using the AsciiMath workflow, even if I open Alfred on my external display, the LaTeX preview still shows up on my MacBook screen.

**Comment by mr-pennyworth** [comment] 2024-02-10 16:41
@joseparreiras `AlfredExtraPane` previously used hacky ways of determining Alfred's position and dimensions. That has since been fixed with correct handling of [press secretary](https://www.alfredforum.com/topic/16111-wip-poc-spotlight-like-rich-preview-pane-for-alfred-workflows/#comment-83222) notifications.

With those changes, I can no longer reproduce the multi-monitor and the misalignment issues.
So, for the moment, I'll assume that the issues are fixed 😇

**Closed** 2024-02-24 17:44 UTC
